packages:
  - extensions/*
  - packages/*
  - docs

catalogs:
  bundling:
    tsup: ^8.3.6
    typescript: ^5.7.3
  deps:
    fast-glob: ^3.3.3
    mathjax-full: ^3.2.2
    pathe: ^2.0.3
    vscode-textmate-languageservice: ^4.0.0
    xstate: ^5.20.0
  dev:
    bumpp: ^10.2.0
    gh-pages: ^6.3.0
    tm-grammars: ^1.24.11
  docs:
    vitepress: ^1.6.3
  lint:
    '@antfu/eslint-config': ^4.2.0
    eslint: ^9.20.0
    jiti: ^2.4.2
    simple-git-hooks: ^2.13.0
  test:
    vitest: ^3.2.4
  types:
    '@types/node': 18.x
  vscode:
    '@vscode/vsce': ^3.6.0
    reactive-vscode: ^0.3.1
    vscode-ext-gen: ^1.0.0

ignoredBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - simple-git-hooks
